### ISSUE TITLE
Create a Login Page and Add to Navbar

### ISSUE THREAD

**Issue by lokytech5** [lokytech5/e-get-why#13]
### Description
We need a new login page for our application. This page should be accessible via a new link in the navigation bar and side content. When the user clicks on this link, they should be taken to the login page.

### Tasks
1. **Create Login Folder:**
   - Create a new folder named login inside the app component directory.
   - Inside the login folder, create a file named page.tsx.

2. **Design the Login Page:**
   - Implement a basic login form within page.tsx.
   - The form should include fields for "Email", "Password",  and a "Submit" button.
   - Style the form using Tailwind CSS and DaisyUI to be consistent with the rest of the application.

3. **Update the Navigation Bar:**
   - Add a new link to the navigation bar for the login page.
   - Ensure the link is consistent with the existing "Home," "Feeds," and "About" links.
   - Also, add the login link below the side content comment in the navbar.

4. **Implement Navigation:**
   - Ensure that clicking the login link will help you navigate to the new login page.

### Additional Notes
- **Branch:** Please create a new branch from `development` for your changes.
  ```bash
  git checkout development
  git pull origin development
  git checkout -b feature/add-login-page
   ```
- Pull Request: Submit a pull request to merge your changes into `development`.
- Testing: Ensure the login page is accessible via the navigation bar and side content. Verify that the form elements are displayed correctly and that the layout is responsive.

**Comment by aedoardo1990** [comment]
hello @lokytech5 I confirm you that I have just created the login page and opened a pull request

**Comment by lokytech5** [comment]
thanks alot for taking tthe time to work on it.

**Comment by aedoardo1990** [comment]
no prob, happy to help!
