### ISSUE TITLE
 Create a Register Page and Add to Navbar

### ISSUE THREAD

**Issue by lokytech5** [lokytech5/e-get-why#14]
### Description
We need a new register page for our application. This page should be accessible via a new link in the navigation bar and side content. When the user clicks on this link, they should be taken to the register page.

### Tasks
1. **Create Register Folder:**
   - Create a new folder named register inside the app component directory.
   - Inside the register folder, create a file named page.tsx.
   
2. **Design the Register Page:**
   - Implement a basic registration form within page.tsx.
   - The form should include fields for "Fullname", "Email", "Username," "Password," and a "Submit" button.
   - Style the form using Tailwind CSS and DaisyUI for consistency with the rest of the application.

3. **Update the Navigation Bar:**
   - Add a new link to the navigation bar for the register page.
   - Ensure the link is consistent with the existing "Home," "Feeds," and "About" links.
   - Also, add the register link below the side content comment in the navbar

### Additional Notes
- **Branch:** Please create a new branch from `development` for your changes.

  ```bash
  git checkout development
  git pull origin development
  git checkout -b feature/add-register-page
   ```
- Pull Request: Submit a pull request to merge your changes into development.
- Testing: Ensure the register page is accessible via the navigation bar and side content. Verify that the form elements are displayed correctly and that the layout is responsive.
- Running the Application: To run the application, navigate to the frontend directory and run:

  ```bash
  npm run dev
  ```

**Comment by aedoardo1990** [comment]
hello @lokytech5, registration page is created and pull request just sent. Should I add as well the logic to handle login and sign up to login and  register pages or are the forms enough so far?

**Comment by lokytech5** [comment]
if you are cool with that and up for the challenge, then is cool with me. I used a serverless framework with AWS cloud formation for the backend of the application. are you up for that?

**Comment by aedoardo1990** [comment]
@lokytech5 for backend so far I have used Django rest framework in other projects but I could google a bit and try it out. If you are fine with that, would it be okay if I'll go ahead with it on next week?

**Comment by lokytech5** [comment]
alright then. I we create an issue on it, and what needs to be done and assign it to you over the weekend and by next week, you can work on it
