### ISSUE TITLE
Redesign Hero Section with Animations

### ISSUE THREAD

**Issue by lokytech5** [lokytech5/e-get-why#15]
### Description
We need to redesign the hero section of our application to make it more visually appealing and engaging. Contributors are welcome to use their imagination and creativity to create a new design with animations.

### Tasks
1. **Analyze Current Hero Section:**
   - Review the existing hero section to understand its structure and content.

2. **Design New Hero Section:**
   - Create a new design for the hero section using Tailwind CSS and DaisyUI for consistency.
   - Include animations to enhance visual appeal and user engagement.
   - The design should be responsive and work well on both desktop and mobile devices.

3. **Understand the Hero Section:**
   - Goto the components directory within the frontend directory; you will see the Hero component
   - Ensure that the animations are smooth and do not hinder performance.

4. **Provide Design Justification:**
   - Write a brief explanation of the design choices and animations used.

### Additional Notes
- **Branch:** Please create a new branch from `development` for your changes.
  ```bash
 git checkout development
 git pull origin development
 git checkout -b feature/redesign-hero-section
   ```
- Pull Request: Submit a pull request to merge your changes into `development`.
- Running the Application: To run the application, navigate to the frontend directory and run:

  ```bash
  npm run dev
  ```

**Comment by aedoardo1990** [comment]
Hello @lokytech5, thanks for the task! I am currently on the road. I will be able to work on it tomorrow afternoon or on Thursday if it is fine for you

**Comment by lokytech5** [comment]
is always fine with me. I want a design for the register and login page. I don't know if you can help me out with that so i can create a new issue on that for you

**Comment by aedoardo1990** [comment]
Sure, I will be happy to help you with that

**Comment by lokytech5** [comment]
I am assigning them to you now. Take your time, and i will be on the lookout for your PR

**Comment by lokytech5** [comment]
@aedoardo1990 I love the login and registration page design so much. thanks

**Comment by lokytech5** [comment]
looking forward to your design for the hero section

**Comment by aedoardo1990** [comment]
Thank you @lokytech5 I am glad you like it!! I have just pulled the request for redesigning the hero page
