### ISSUE TITLE
Set Up Zustand for State Management with TypeScript

### ISSUE THREAD

**Issue by lokytech5** [lokytech5/e-get-why#19]
### Description
This task's goal is to install Zustand for state management and create a file called `useUserStore.ts` to store user information in our application. This file will be the foundation for managing user state across the application using TypeScript.

### Tasks
1. **Install Zustand:**
   - Install Zustand using npm.
     ```bash
     npm install zustand
     ```

2. **Create Zustand Store:**
   - Create a new file called `useUserStore.ts` in the `app/components` directory.
   - Define the `User` and `UserState` interfaces.
   - Implement the Zustand store to manage user state.

3. **Define the User and UserState Interfaces:**
   - Add the following code to `useUserStore.ts`:
     ```typescript
     interface User {
       userId: string;
       username: string;
       email: string;
       fullName: string;
       profilePictureURL?: string;
       bio?: string;
       location?: string;
     }

     interface UserState {
       user: User | null;
       token: string | null;
       setUser: (user: User) => void;
       setToken: (token: string) => void;
       clearUser: () => void;
     }
     ```

4. **Implement the Zustand Store:**
   - Add the following code to `useUserStore.ts` to create the Zustand store:
     ```typescript
     import create from 'zustand';

     export const useUserStore = create<UserState>((set) => ({
       user: null,
       token: null,
       setUser: (user) => set({ user }),
       setToken: (token) => set({ token }),
       clearUser: () => set({ user: null, token: null }),
     }));
     ```

5. **Usage Example:**
   - Here is an example of how to use the Zustand store in a component:
     ```typescript
     import React from 'react';
     import { useUserStore } from './component/useUserStore';

     const UserProfile: React.FC = () => {
       const { user, token, setUser, setToken, clearUser } = useUserStore();

       return (
         <div>
           <h1>User Profile</h1>
           {user ? (
             <div>
               <p>Username: {user.username}</p>
               <p>Email: {user.email}</p>
               {/* Add more user information as needed */}
               <button onClick={clearUser}>Logout</button>
             </div>
           ) : (
             <p>Please log in.</p>
           )}
         </div>
       );
     };

     export default UserProfile;
     ```

### Additional Notes
- **Branch:** Please create a new branch from `feature/auth` for your changes.
  ```bash
  git checkout feature/auth
  git pull origin feature/auth
  git checkout -b feature/setup-zustand
   ```

- Pull Request: Submit a pull request to merge your changes into `development`.
- Running the Application: To run the application, navigate to the frontend directory and run:

  ```bash
  npm run dev
  ```

**Comment by lokytech5** [comment]
@aedoardo1990, since you mention to work on the login and register page functionality, i hope this layout will give you a general overview of how we can handle users state within the application

**Comment by aedoardo1990** [comment]
hello @lokytech5 thanks a lot for the detailed intructions! I have just submitted the pull request

**Comment by lokytech5** [comment]
Ok i we go through it and merge. just for reference, I am creating a new issue on the api-client. i we provide you with the actual endpoint

**Comment by aedoardo1990** [comment]
ok great, looking forward!
