### ISSUE TITLE
Set Up Axios API Client

### ISSUE THREAD

**Issue by lokytech5** [lokytech5/e-get-why#21]
### Description
This task's goal is to install Axios for making HTTP requests and create an API client to handle interactions with the backend. The API client will be used throughout the application for making network requests.

### Tasks
1. Navigate to the forntend folder from your terminal with this command
   ```bash
      cd frontend
   ```

2. **Install Axios:**
   - Install Axios using npm.
     ```bash
     npm install axios
     ```

3. **Create API Client:**
   - Create a new file called `apiClient.ts` in the `app/components` directory.
   - Set up an Axios instance with a base URL and necessary headers.
   - Use the following base URL for the Axios instance: `https://olikwzthj7.execute-api.us-east-1.amazonaws.com/dev`.
   - Add meaningful comments when setting up the Axios instance.

4. **Implement Interceptors:**
   - Add interceptors to handle request and response globally.
   - Ensure to include authorization tokens in requests.
   - Handle errors globally, such as redirecting to login on 401 errors.

### Additional Notes
- **Branch:** Please create a new branch from `development` for your changes.
  ```bash
  git checkout development
  git pull origin development
  git checkout -b feature/setup-axios

**Comment by aedoardo1990** [comment]
good morning @lokytech5! I have created the merge request

**Comment by lokytech5** [comment]
good morning, hope you good
