### ISSUE TITLE
Set Up Toast Notifications with react-toastify

### ISSUE THREAD

**Issue by lokytech5** [lokytech5/e-get-why#23]
### Description
This task aims to install `react-toastify` for toast notifications and create a toast component to display notifications across the application.

### Tasks
1. **Navigate to the frontend folder using this command**
    ```bash
     cd frontend
    ```

2. **Install react-toastify:**
   - Install `react-toastify` using npm.
     ```bash
     npm install react-toastify
     ```

3. **Set Up Toast Notifications:**
   - Create a new file called `ToastNotify.tsx` in the `app/components` directory.
   - Configure the `ToastContainer` component.
   - Create a utility function to display different types of toast notifications.

4. **Integrate Toast Container in Layout Component:**
   - Ensure the `ToastContainer` is included in layout component.

### Additional Notes
- **Branch:** Please create a new branch from `development` for your changes.

  ```bash
  git checkout development
  git pull origin development
  git checkout -b feature/setup-toast-notifications

- Pull Request: Submit a pull request to merge your changes into `development`.
- Testing: Ensure the toast notifications work correctly by displaying different types of notifications (success, error, info, warning).

### Guidelines to Follow:
**Create `ToastNotify.tsx`:**
- Use the following code as a starting point:

```bash
     import React from 'react';
     import { ToastContainer, toast } from 'react-toastify';
     const ToastNotify = () => {
       return <ToastContainer position="bottom-right" autoClose={5000} hideProgressBar={false} newestOnTop={false} 
     closeOnClick={true} draggable={true} pauseOnHover={true} />;
     };

     export default ToastNotify;
```

**Create Utility Functions for Toast Notifications:**
   - Create a new folder called utils in the `component` directory
   - Create a new file called `toastUtils.ts` in the `component/utils` directory.
   - Add utility functions for displaying different types of toast notifications:
 
     ```bash
     import { toast } from 'react-toastify';

     export const showToastSuccess = (message: string) => {
       toast.success(message);
     };
     
     ```
- Do the same for error, info and warning

**Integrate Toast Container in Layout Component:**

   - Ensure the `ToastContainer` is included in layout component (e.g., `Layout.tsx`):
 
 ```bash
     import ToastNotify from './components/ToastNotify';
     import 'react-toastify/dist/ReactToastify.css';
     return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
      <div className="min-h-screen bg-base-300 flex flex-col">
          <Navbar />
          <div className="flex-grow">{children}</div>
          <Footer />
        </div>
        <ToastNotify />
        </Providers>
        </body>
    </html>
  )

 ```

**Comment by lokytech5** [comment]
let me know if there is anything not clear.

**Comment by aedoardo1990** [comment]
good morning @lokytech5 , sure! working on it

**Comment by aedoardo1990** [comment]
pull request open

**Comment by lokytech5** [comment]
good day @aedoardo1990. am checking the pr
