### ISSUE TITLE
Create Custom Hook for Register Endpoint using React Query

### ISSUE THREAD

**Issue by lokytech5** [lokytech5/e-get-why#25]
### Description
This task aims to create a custom hook using React Query to handle the registration endpoint. The custom hook will make a POST request to the provided URL and handle the response appropriately.

### Tasks
1. **Navigate to the frontend folder using this command**
    ```bash
     cd frontend
    ```

2. **Create Custom Hook for Register Endpoint:**
   - Create a folder called hooks in the `app` directory.
   - Create a new file called `useRegister.ts` in the `app/hooks` directory.
   - Set up a custom hook using React Query to handle the registration process.

3. **Integrate Custom Hook in Register Component:**
   - Ensure the custom hook is used in the Register component to handle the form submission.

### Additional Notes
- **Branch:** Please create a new branch from `development` for your changes.

  ```bash
  git checkout development
  git pull origin development
  git checkout -b feature/create-register-hook

- Pull Request: Submit a pull request to merge your changes into `development`.
- Testing: Ensure the custom hook works correctly by handling the registration process and providing appropriate feedback.

### Guidelines to Follow:
**Create `useRegister.ts:**
- Use the following code as a starting point:
```bash
import { useMutation } from '@tanstack/react-query';
import apiClient from '../utils/apiClient';

interface RegisterData {
  username: string;
  email: string;
  password: string;
  fullName: string;
}

export const useRegister = () => {
  return useMutation(
    async (registerData: RegisterData) => {
      const response = await apiClient.post('/auth/signup', registerData);
      return response.data;
    },
    {
      onSuccess: (data) => {
      // Import success toast here
        
      },
      onError: (error) => {
     //import error toast here
        
      },
    }
  );
};
```
- example of the appropriate toast to be imported
```bash
showToastSuccess('Registration successful!');
showToastError('Registration failed. Please try again.');
```
- Integrate Custom Hook in Register Component
- Ensure the custom hook is used in the Register component to handle the form submission

**Comment by aedoardo1990** [comment]
@lokytech5 I have opened a pull request. I have designed the hook and the loading spinner so by checking  https://github.com/lokytech5/techdoc/tree/main . Should I include error handling as well in the hook and register page by following what you created in techdoc?
