### ISSUE TITLE
Good First Issue: Install and Set Up DaisyUI Theme

### ISSUE THREAD

**Issue by lokytech5** [lokytech5/e-get-why#5]
### Description
We are looking for a new contributor to help us install and configure the DaisyUI theme for our project. DaisyUI is a Tailwind CSS component library that will help us style the project quickly. This is a great first issue for someone new to the project and wanting to get started.

### Tasks
1. **Install DaisyUI:**
   - Install the DaisyUI package using npm.
     ```bash
     cd frontend
     npm i -D daisyui@latest
     ```

2. **Configure Tailwind CSS:**
   - Add daisyUI to tailwind.config.js:
     ```javascript
     // tailwind.config.js
     module.exports = {
       plugins: [
               require('daisyui')
                  ],
     }
     ```

3. **Verify Installation:**
   - Verify that DaisyUI is working by using some DaisyUI components in a sample page. Create a new component or update an existing component to use DaisyUI classes.
   - e.g `<button class="btn btn-primary">Button</button>`

### Additional Notes
- **Branch:** Please create a new branch from `feature/website-theme` for your changes.
  ```bash
  git checkout feature/website-theme
  git pull origin feature/website-theme
  git checkout -b feature/setup-daisyui
  ```
- Pull Request: Submit a pull request to merge your changes back into feature/website-theme.
- Testing: Make sure the application builds and runs without errors after your changes.

### Resources
- [DaisyUI Documentation](https://daisyui.com/docs/install/)

**Comment by aedoardo1990** [comment]
Hello @lokytech5! Nice to meet you! May I work on the issue? I am a newly graduated full stack developer based in Germany.

**Comment by cpwallah** [comment]
hi @lokytech5 made a pr in which i have implemented daisyui

**Comment by lokytech5** [comment]
hello @aedoardo1990,  thank you for your interest, @cpwallah already made a PR. i we be opening more good first issue today, and am going to assign you a task soon. thank you

**Comment by aedoardo1990** [comment]
hello @lokytech5 thanks for your reply and for inviting me to collaborate! I have just accepted the invitation. Whenever you want, feel free to assign me a task or if you prefer, I could assign one of the free ones to myself.

**Comment by lokytech5** [comment]
You welcome. I have assigned you a task to work on
