### ISSUE TITLE
 Implement a Responsive Navigation Bar

### ISSUE THREAD

**Issue by lokytech5** [lokytech5/e-get-why#7]
### Description
We need a responsive navigation bar for our application. The bar should include links to "Home," "About," "Services," and "Contact."

### Tasks
1. **Design the Navigation Bar:**
   - Use Tailwind CSS and DaisyUI to design a responsive navigation bar.
   - Include placeholder links for "Home", "About", "Services", and "Contact".

2. **Implement the Navigation Bar:**
   - Create a new React component for the navigation bar.
   - Ensure it is responsive and works well on desktop and mobile devices.
   - Add meaningful comments when starting the navigation bar implementation.

3. **Integrate the Navigation Bar:**
   - Add the navigation bar component to the main layout of the application.

### Additional Notes
- **Branch:** Please create a new branch from `feature/website-theme` for your changes.
  ```bash
  git checkout feature/website-theme
  git pull origin feature/website-theme
  git checkout -b feature/create-navbar
   ```
- Pull Request: Submit a pull request to merge your changes into feature/website-theme.
- Testing: Ensure the navigation bar appears correctly on different screen sizes, and the 
    links work.

**Comment by aedoardo1990** [comment]
hello @lokytech5, thanks for the tasks! I have started to work on it but I won't be able to finish this weekend as I will be busy. Is it fine if I will continue on Monday?

**Comment by lokytech5** [comment]
That sounds good to me. Have fun over the weekend

**Comment by aedoardo1990** [comment]
Thank you @lokytech5, have a good weekend as well :)

**Comment by aedoardo1990** [comment]
Hello @lokytech5, I hope you are doing well. I have created the navbar and I am trying to submit a pull request. I have the following issue when I am trying to give the command "git pull origin feature/website-theme" --> 

"fatal: couldn't find remote ref feature/website-theme"

I have tried different things but so far they haven't worked out. Could you pls help me to fix the issue?

Regards

**Comment by aedoardo1990** [comment]
@lokytech5 you can disregard my previous message, I have just submitted a pull request for the navbar. If you have any doubts, let me know.

**Comment by lokytech5** [comment]
@aedoardo1990 thanks for the pr, i we look through it and fix the issue with the branch

**Comment by lokytech5** [comment]
I have seen the changes made, and they were okay. Regarding the earlier error, my backend serverless application broke my workflow, and I am working on it. For the next task, you can create a new branch for that.

**Comment by lokytech5** [comment]
Am updating the site with your new change

**Comment by aedoardo1990** [comment]
all right, thank you @lokytech5! :)

**Comment by lokytech5** [comment]
Should i assign you the last issue?

**Comment by lokytech5** [comment]
or should i open an issue for the serverless backend am working on

**Comment by aedoardo1990** [comment]
@lokytech5 sure, you can assign it to me. I will work on it tomorrow
