### ISSUE TITLE
Design and Implement a Home Page Banner

### ISSUE THREAD

**Issue by lokytech5** [lokytech5/e-get-why#8]
### Description
We need a visually appealing banner for the home page. The banner should include a catchy slogan and a call-to-action button.

### Tasks
1. **Design the Banner:**
   - Use Tailwind CSS and DaisyUI to design a responsive banner.
   - Include a catchy slogan and a call-to-action button.

2. **Implement the Banner:**
   - Create a new React component for the banner.
   - Ensure it is responsive and works well on desktop and mobile devices.

3. **Integrate the Banner:**
   - Add the banner component to the home page layout.

### Additional Notes
- **Branch:** Please create a new branch from `feature/website-theme` for your changes.
  ```bash
  git checkout feature/website-theme
  git pull origin feature/website-theme
  git checkout -b feature/create-homepage-banner
   ```
- Pull Request: Submit a pull request to merge your changes into feature/website-theme.

**Comment by lokytech5** [comment]
@aedoardo1990 you can start working on this

**Comment by aedoardo1990** [comment]
@lokytech5 I have just created the Home Page Banner and submitted the pull request. Should you have any doubts or something should be modified, feel free to ask

**Comment by lokytech5** [comment]
ok am currently reviewing the code
