### ISSUE TITLE
Set Up DaisyUI Theme called night

### ISSUE THREAD

**Issue by lokytech5** [lokytech5/e-get-why#9]
### Description
We are looking for a new contributor to help us configure the DaisyUI theme for our project. DaisyUI is a Tailwind CSS component library that provides a set of ready-to-use components and themes. This is a great first issue for someone new to the project and wanting to start.

### Tasks
1. **Update tailwind.config.js to include DaisyUI themes:**
    - Add the following configuration to tailwind.config.js:  
  ```javascript
   module.exports = {
  // other configurations...
  plugins: [require("daisyui")],
  daisyui: {
    themes: ["night"],
  },
};
  ```

2. **Ensure the configuration is added below other plugins:**
   - The plugins array should look like this:
 ```javascript
     plugins: [
  // other plugins...
  require("daisyui"),
],
daisyui: {
  themes: ["night"],
},
 ```

3.  **Test the theme configuration:**
-  Switch between different themes (e.g., "cupcake", "light", "forest") and ensure they are applied correctly.

### Additional Notes
- **Branch:** Please create a new branch from `feature/website-theme` for your changes.
  ```bash
  git checkout feature/website-theme
  git pull origin feature/website-theme
  git checkout -b feature/add-theme
   ```
- Pull Request: Submit a pull request to merge your changes into feature/website-theme.
- Testing: Ensure the theme changes are reflected correctly by testing different themes.

**Comment by aedoardo1990** [comment]
hello @lokytech5, I have created the merge request.

**Comment by lokytech5** [comment]
ok am going through it now
